# fly.toml app configuration file generated for wallet-money-auth-service on 2024-03-27T18:27:02+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wallet-money-auth-service'
primary_region = 'ams'

[experimental]

[build]

[http_service]
  internal_port = 80
  processes = ['app']
  min_machines_running = 0
  auto_stop_machines = true

[[vm]]
  memory = '1024MB'
  cpu_kind = 'shared'
  cpus = 1

[max_instances]
count = 1
